export const REPOSITORY_INJECTION_TOKEN = {
  CUSTOMER: 'CUSTOMER',
  ORDER: 'ORDER',
  PRODUCT: 'PRODUCT',
  SHIPMENT: 'SHIPMENT',
  WAREHOUSE: 'WAREHOUSE',
  STORE: 'STORE',
  SUPPLIER_PRODUCT: 'SUPPLIER_PRODUCT',
  SUPPLIER: 'SUPPLIER',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ORDER_DETAIL: 'ORDER_DETAIL',
  EMPLOYEE: 'EMPLOYEE',
}

export const SERVICE_INJECTION_TOKEN = {
  CUSTOMER: 'CUSTOMER',
  ORDER: 'ORDER',
  PRODUCT: 'PRODUCT',
  SHIPMENT: 'SHIPMENT',
  WAREHOUSE: 'WAREHOUSE',
  STORE: 'STORE',
  SUPPLIER_PRODUCT: 'SUPPLIER_PRODUCT',
  SUPPLIER: 'SUPPLIER',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ORDER_DETAIL: 'ORDER_DETAIL',
  EMPLOYEE: 'EMPLOYEE',
}
