export enum ENUM_USER_ROLE {
  STUDENT = 'STUDENT',
  TUTOR = 'TUTOR',
  ADMIN = 'ADMIN'
}

export enum ENUM_USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ANONYMOUS = 'ANONYMOUS'
}

export enum ENUM_ONBOARDING_STATUS {
  IN_PROGRESS = 'IN_PROGRESS',
  SKIPPED = 'SKIPPED',
  COMPLETED = 'COMPLETED'
}